import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TarefasProvider } from "@/context/TarefasContext";

const poppins = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "400 900", 
});

export const metadata: Metadata = {
  title: "Taskly!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <TarefasProvider>{children}</TarefasProvider>
      </body>
    </html>
  );
}
